version:  0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
      commands:
        - mv build/libs/gdrive2workdocs-all-*.jar build/gdrive2workdocs.jar

artifacts:
  files:
    - 'build/gdrive2workdocs.jar'
