workdocs:
  - name: my-workdocs-org
    userQuery: my-user-query
    region: eu-west-1
    organisationId: d-123abc
    accessKey: ABC123
    secretKey: ABC123


gdrives:
  - name: MyGDrive
    applicationName: GDrive to AWS Workdocs
    clientId: abc123.apps.googleusercontent.com
    clientSecret: abc123
    destination: my-workdocs-org
    fileFetchSize: 1000
    downloadOnly: false
    cleanup: true
    dontDeleteDir:
      - /keep-these-gdrive-folder
    targetDirName: My-GDrive-Files

mimeTypes:
  docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
  odt: application/vnd.oasis.opendocument.text
  ods: application/x-vnd.oasis.opendocument.spreadsheet
  odp: application/vnd.oasis.opendocument.presentation
  pdf: application/pdf
  png: image/png
  svg: image/svg+xml

settings:
  dataStoreDir: /gdrive2workdocs